version: '3.5'

services:
  app:
    image: node:16.13-slim
    command: [npm, start]
    ports:
      - 3000:3000
    expose:
      - 3000
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - kvs
  kvs:
    image: redis:7.0.4
    ports:
      - 6379:6379
    expose:
      - 6379
