version: '3.5'

services:
  app:
    build: .
    init: true
    ports:
      - 3000:3000
    entrypoint:
      - node
      - ./bin/www
    expose:
      - 3000
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - kvs
  kvs:
    image: redis:7.0.4
    ports:
      - 6379:6379
    expose:
      - 6379
  doc:
    image: asyncapi/studio
    ports:
      - 8080:80
    expose:
      - 8080
